server.port=${PORT:8080}
logging.level.org.atmosphere=warn

# Launch the default browser when starting the application in development mode
vaadin.launch-browser=true

# Package tempat Vaadin nyari view/route punya lu (buat hot-reload di dev mode)
vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,property24

# --- Koneksi ke MySQL ---
# Ganti NAMA_DB_LU sesuai nama database yang udah lu buat sendiri
spring.datasource.url=jdbc:mysql://localhost:3306/aset_24
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# update = Hibernate akan membuat/memperbarui tabel baru jika belum ada tanpa menghapus data
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --- Konfigurasi Email (Gmail SMTP) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fachriachmad575@gmail.com
spring.mail.password=rtpr etbi ekdr saba
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
